config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  get 'dashboard/show'
  get "me", to: "dashboard#show"
  get 'design', to: 'pages#design'
  resources :pets do
    resources :bookings, only: [:create, :destroy ]
  end
  resources 'profile', only: [:show, :edit, :update]
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
  validates :description, presence: true
  validates :age, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 200 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  validates :species, presence: true, inclusion: {in: %w(cat dog bird elephant fish hamster giraffe monkey snake spider)}

  # geocoded_by :user.location
  # after_validation :geocode, if: :will_save_change_to_location?

  def self.categories
    %w(cat dog elephant fish hamster giraffe monkey snake spider)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    animal_species = params[:animal].singularize
    # raise params[:animal].singularize.inspect
    if params[:animal].present? && Pet.exists?(species: animal_species)
      @pets = Pet.where(species: animal_species)
    elsif params[:animal].present? && Pet.exists?(species: animal_species) == false
      flash[:alert] = "Sorry we don't have #{params[:animal]}"
      redirect_to root_path
    else
      @pets = Pet.all
    end

    @markers = @pets.map do |pet|
      {
        lat: pet.user.latitude,
        lng: pet.user.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @booking = Booking.new
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end


  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :description, :age, :species, :price, :photo)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/views/pets/create.html.erb
<h1>Pets#create</h1>
<p>Find me in app/views/pets/create.html.erb</p>

app/views/pets/destroy.html.erb
<h1>Pets#destroy</h1>
<p>Find me in app/views/pets/destroy.html.erb</p>

app/views/pets/edit.html.erb
<h1>Pets#edit</h1>
<p>Find me in app/views/pets/edit.html.erb</p>

app/views/pets/index.html.erb
<h1 class="text-center">we found those <%= params[:animal] %></h1>
<div class="container">
  <div class="row">
   <div class="col-xs-6">
    <% @pets.each do |pet| %>
      <div class="col-xs-12 col-sm-6">
        <%= render partial: 'shared/pet-card', locals: { pet: pet } %>
      </div>
    <% end %>
  </div>
  <div>
    <div class="text-center">
      <div
        id="map"
        style="width: 50%;
        height: 600px;
        margin-top: 24px;"
        data-markers="<%= @markers.to_json %>"
      ></div>
    </div>
  </div>
  </div> <!-- clos row -->
</div><!-- close container -->

app/views/pets/new.html.erb
<div class="form-background">
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-xs-offset-3">
        <div class="form-wrapper">

          <h1>Sign-up your pet</h1>

          <%= simple_form_for(@pet, method: "post") do |f| %>
            <%= f.input :name %>

            <div class="row">
              <div class="col-xs-4"> <%= f.input :age %> </div>
              <div class="col-xs-4">   <%= f.input :species,
              collection: %w(cat dog elephant fish hamster giraffe monkey snake spider bird) %>
                </div>
              <div class="col-xs-4"> <%= f.input :price, label: "Price/day in DKK", as: :numeric %> </div>
            </div>
            <%= f.input :description, :input_html => { :rows => 5 } %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>

            <div class="form-actions">
              <%= f.button :submit, "Sign-up", class: "btn btn-info" %>
            </div>
          <% end %>

        </div> <!-- end form wrapper -->
      </div> <!-- end column-->
    </div> <!-- end row -->
  </div> <!-- end container -->
</div>

app/views/pets/show.html.erb
<div class="container pet_container">
  <div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
      <div class="big-part">
        <div class="row">
          <div class="col-xs-2"></div>
          <div class="col-xs-8">
            <div class="pet_picture">
               <%= cl_image_tag(@pet.photo, width: 300, height: 250, crop: :fill) %>
            </div>
          </div>
          <div class="col-xs-2"></div>
         </div> <!-- close row -->

        <div class="row">
          <div class="col-xs-2"></div>
          <div class="col-xs-8">
            <div class="pet_attributes">
              <h2><%= @pet.name %></h2>
                <ul class="list-unstyled">
                  <li><%= @pet.species.capitalize %></li>
                  <li>Is <%= @pet.age %> years old</li>
                  <li>Belongs to <%= @pet.user.name %></li>
                  <li>Lives in <%= @pet.user.location %></li>
                </ul>
            </div>
            <div class="pet_description">
              <p><%= @pet.description %></p>
            </div>
          </div>
          <div class="col-xs-2"></div>
        </div><!-- close row -->
      </div>
    </div>
    <div class="col-xs-2"></div>
  </div> <!-- close big row -->
    <div class="row">
      <div class="col-xs-2"></div>
      <div class="col-xs-8">
        <div class="pet_booking_box">
          <h2>Schedule</h2>
          <h4>DKK <%= @pet.price %> per day</h4>
          <%= simple_form_for([@pet, @booking], url: pet_bookings_path(@pet), method: :post) do |f| %>
            <%= f.input :date_from, label: "Pick-up", as: :string, input_html: { data: {provide: "datepicker"} }  %>
            <%= f.input :date_to, label: "Drop-off", as: :string, input_html: { data: {provide: "datepicker"} }  %>
                <br>
            <div class="form-actions">
                  <%= f.button :submit, "Book", class: "btn btn-success" %>
            </div>
              <% end %>
        </div>
      </div>
      <div class="col-xs-2"></div>
    </div><!-- close row -->
</div> <!-- container -->

app/views/pets/update.html.erb
<h1>Pets#update</h1>
<p>Find me in app/views/pets/update.html.erb</p>