config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  get 'dashboard/show'
  get "me", to: "dashboard#show"
  get 'design', to: 'pages#design'
  resources :pets do
    resources :bookings, only: [:create, :destroy ]
  end
  resources 'profile', only: [:show, :edit, :update]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/eumar-8/pet_rbnb"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fa fa-heart"></i> from Eugenia & Susanne
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logoPet1.jpg", height: 65 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Dashboard", "/me", class: "navbar-wagon-item navbar-wagon-link" %>
      <%-# link_to "Avatar", "#", class: "navbar-wagon-item navbar-wagon-link" -%>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo? %>

          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>





          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to  profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to  edit_profile_path(current_user) do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Edit profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_pet-card.html.erb
<div class="home-card">
  <% if pet.photo? %>
  <div class="card-header" style="background-image: url(<%= image_path(pet.photo) %>);">
  </div>
  <% else %>
  <div class="card-header" style="background-image: url(<%= image_path("monkey.jpg") %>);">
  </div>
  <% end %>

  <div class="card-content">
    <p><%= link_to pet.name, pet_path(pet), class: "card-link" %></p>
    <p><%=pet.description%></p>

    <div class="card-user-details">
      <!-- <img src='https://kitt.lewagon.com/placeholder/users/krokrob' class="avatar-large"/> -->
      <%= image_tag pet.user.photo, class: "avatar-large" %>
      <div class= "card-user-content">
        <p><%=pet.user.name%></p>
        <p><%=pet.user.location%></p>
      </div>
    </div>

    <div class="card-body">

    </div>
  </div>
</div>