config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  get 'dashboard/show'
  get "me", to: "dashboard#show"
  get 'design', to: 'pages#design'
  resources :pets do
    resources :bookings, only: [:create, :destroy ]
  end
  resources 'profile', only: [:show, :edit, :update]
end

app/views/pages/design.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path("dogs-background.jpg") %>);">
  <div class="banner-content">

   <h1> ALL THE PETS LOVE YOU CAN HANDLE</h1>
    <div class="search-container">
      <%= form_tag("/search", class: "search-form") do %>
          <%= text_field_tag(:q, nil, placeholder: "Search for dog, cat or elephant")%>
          <a href="" class="search-button">
            <span><i class="fa fa-search"></i></span>
          </a>
       <% end %>
      </div>
      <p>
        <span id="banner-typed-text"></span>
      </p>

    </div>
  </div>
</div>
<img src='https://kitt.lewagon.com/placeholder/users/ssaunier' class="avatar-large"/>

<form action="">
  <div class="form-inputs">
    <input type="text" class="super-input">
  </div>
</form>

  <div class="form-actions">
    <a href="" class="btn btn-primary btn-lg">Submit</a>
  </div>

<input type="text" data-provide='datepicker' >

app/views/pages/home.html.erb
<div class="banner" style= "background-image:url(<%=image_path("dogs-background.jpg")%>);">
  <div class="banner-content">

   <h1> ALL THE PETS LOVE YOU CAN HANDLE</h1>
   <!-- <button id="sweet-alert-demo" class="btn btn-primary">Click me!</button> -->
    <div class="search-container">
    <%= form_tag(pets_path, class: "search-form", method: :get) do %>
        <%= text_field_tag(:animal, nil, placeholder: "Search for dog, cat or elephant")%>
        <a href="" class="search-button">
          <span id="sweet-alert-demo"><i class="fa fa-search"></i></span>
        </a>
     <% end %>
    </div>
    <p>
      <span id="banner-typed-text"></span>
    </p>

  </div>
</div>

<div class="container">
  <div class="row">
    <% @pets.each do |pet| %>
      <div class="col-xs-12 col-sm-4">
        <%= render partial: 'shared/pet-card', locals: { pet: pet } %>
      </div>
    <% end %>

  </div>
</div>

<br><br>
<%= link_to "Add your pet", new_pet_path, class: "btn btn-info" %>